agiledev-students-fall2024/4-final-project-while-we-were-dreaming

front-end/src/assets/styles/About.css, front-end/src/assets/styles/App.css, front-end/src/pages/About.js
Fixed the footer to extend to the end of page, Formatted About us but still needs image
=> Fixed the footer to extend to the end of page, Formatted About us

front-end/src/assets/styles/About.css, front-end/src/pages/About.js
Added Feedback and Contact Buttons with formatting in About page
=> Added Feedback and Contact Buttons in About

front-end/src/App.js, front-end/src/pages/About.js, front-end/src/pages/Contact.js
=> contact page

front-end/src/assets/styles/App.css
Let all pages be scrollable (now home, register,  etc. should be now visible  to end of page)
=> Pages are now scrollable 

front-end/src/assets/styles/About.css, front-end/src/assets/styles/Feedback.css, front-end/src/pages/Contact.js, front-end/src/pages/Feedback.js
Added and formatted back buttons for Register and Contact Page to go back to previous 'About' page, helps links both Register and Contact pages tother
Edited Register page to have required fields, and unified the button color with Contact Page
=> Added and formatted back buttons for Register and Contact Page, Register page has required fields

front-end/src/assets/styles/App.css, front-end/src/pages/Header.js
Header controls container for both Login button and Hamburger. Button takes you to login, Login button still needs to update to profile when logged in
=> Login button in top header 

front-end/src/assets/styles/App.css, front-end/src/pages/Feedback.js, front-end/src/pages/Header.js
Unified Feedback and Contact Formatting,
Pressing on the logo in header will take you to home.
=> Response message and Handle submission for Feedback

README.md
=> Update README.md with build and testing instructions

front-end/src/App.js, front-end/src/pages/Header.js, front-end/src/pages/ModifyPins.js
added modify pins page frontend
=> created modify pins page

back-end/app.js, back-end/routes/feedbackroutes.js, front-end/src/assets/styles/Feedback.css, front-end/src/pages/Feedback.js
Updated State handling for Feedback Page to reflect Server Feedback, New pages (states) to display a successful or failed submission.
=> Created back route for Feedback, and Integrated it with Front-end page

back-end/app.js, back-end/routes/contactroutes.js, back-end/routes/feedbackroutes.js, front-end/src/assets/styles/About.css, front-end/src/assets/styles/Feedback.css, front-end/src/pages/Contact.js, front-end/src/pages/Feedback.js
State handling for response page based on Backend response.
Modified formatting for Feedback and Contacts with new pages.
=> Created new route for Contact. Integrated w/ Front end Contacts page.

back-end/package.json, back-end/routes/contactroutes.js, back-end/routes/feedbackroutes.js, back-end/routes/mockContactData.json, back-end/routes/mockFeedbackData.json, back-end/test/formRoutes.test.js
created mock data and dynamic routes for feedback and contact forms; tested with mocha
=> dynamic routes for mock data - feedback and contact forms

back-end/routes/userroutes.js, front-end/src/App.js, front-end/src/PinContext.js, front-end/src/components/Map.js, front-end/src/pages/ModifyPins.js
Front-Back end integration are also synchronized for both pages.
=> Synchronized Pins in Home Page and Modify pins with PinContext.

back-end/routes/friends.js, package.json
i might need some help im sorry
=> (tried to?) fixed dynamic routing for friends

back-end/package.json, front-end/src/pages/Register.js
added extra parameters for registration and error handling
=> Registration JWT Auth Update

back-end/validators/contactValidator.js, back-end/validators/userValidator.js, front-end/src/pages/Contact.js, front-end/src/pages/Feedback.js
enhanced backend validation for contact feedback and user froms
=> updated validators

back-end/routes/pinroutes.js, front-end/src/PinContext.js, front-end/src/components/pinModal.js, front-end/src/pages/ModifyPins.js
Deletes and updates pins according to MongoDB data. Fixed textfield bug: Textfield now resets after submitting new pin.
=> Deletes and updates pins according to MongoDB data

front-end/src/assets/styles/ModifyPins.css, front-end/src/pages/Feedback.js, front-end/src/pages/ModifyPins.js
Cleared up lines in  Modify Pins formatting to ease up writing code in file integrating with MongoDB , Updated Feedback Page.
=> Updated Modify Pins formatting , Updated Feedback Page

front-end/package.json, front-end/src/pages/Feedback.js
feedback form now autogenerates email with feedback and sends via emailjs api
=> Added Feedbackform Functionality 

README.md, front-end/package.json, front-end/src/pages/Contact.js
contactform now has user input send email using api
=> added contactform functionality

back-end/app.js, back-end/models/User.js, back-end/routes/friends.js, back-end/routes/notifications.js, front-end/package.json
added notification feature. user entry in DB gains a new "notification" when the user is added as a friend
=> Notifications

front-end/src/assets/styles/login.css, front-end/src/components/MapSettings.js
Fixed compressed CSS on login window, changed Pin view toggler to more accurately reflect what it does. This is because I was unable to fix the buttons function where it saves the proper state as a sessions variable. **When the map reloads, the pins show up again, so the map setting are not saved in session. Just the visual toggle settings.**
=> CSS & JS Fix

front-end/src/components/MapSettings.js, front-end/src/pages/UserSettings.js
this pr can be reverted in the future if needed
=> remove friends implementation due to incompletion

front-end/src/components/form.js, front-end/src/pages/About.js
added extra features to form.js and about page
=> small frontend tweaks

front-end/src/components/Map.js, front-end/src/pages/Header.js
ruins the desktop version but just for the presentation...
=> fixed formatting for mobile

front-end/src/assets/styles/register.css
=> adjust ui#2
